## SPLITTING

In [2]:
import numpy as np

In [3]:
l = [5,10,15,20,25,30,35,40]
l

[5, 10, 15, 20, 25, 30, 35, 40]

In [4]:
x,y,z, = np.split(l,[2,6])
print(x)
print(y)
print(z)

[ 5 10]
[15 20 25 30]
[35 40]


### vsplit 

VERTICAL SPLIT

In [4]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
np.vsplit(x,[3])

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

In [9]:
np.vsplit(x,[2])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [6]:
np.vsplit(x,[3])[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
np.vsplit(x,[1])[1]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### hsplit

HORIZONTAL SPLIT

In [9]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [10]:
np.hsplit(a,[1])

[array([[ 0],
        [10]]),
 array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [13]:
np.hsplit(a,[3])

[array([[ 0,  1,  2],
        [10, 11, 12]]),
 array([[ 3,  4,  5,  6,  7,  8,  9],
        [13, 14, 15, 16, 17, 18, 19]])]

In [12]:
np.hsplit(a,[3])[1]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19]])

In [14]:
x,y,z = np.hsplit(a,[2,6])

In [15]:
print(x)
print(y)
print(z)

[[ 0  1]
 [10 11]]
[[ 2  3  4  5]
 [12 13 14 15]]
[[ 6  7  8  9]
 [16 17 18 19]]


## SORTING 

In [28]:
a = np.array([3,78,56,12,9])
a

array([ 3, 78, 56, 12,  9])

In [29]:
np.sort(a) #not update a

array([ 3,  9, 12, 56, 78])

In [30]:
a

array([ 3, 78, 56, 12,  9])

**BUT**

In [31]:
a.sort() #update a

In [32]:
a

array([ 3,  9, 12, 56, 78])

### argsort 

[0,1,2,3,4,5]  correct sort

[5,2,0,3,4,1]  the list

[2,5,1,3,4,0]  indexes

In [34]:
a = [5,2,0,3,4,1]
np.argsort(a)

array([2, 5, 1, 3, 4, 0])

## INDEXING

In [39]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [40]:
a[0][2]

3

**OR**

In [42]:
a[0,2]

3

In [45]:
a[1,2] = 288 
a

array([[  1,   2,   3,   4,   5],
       [  6,   7, 288,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

### Slice Indexing 

In [46]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [47]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
a[::-1]

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

[row,column]

In [50]:
a[:,3] #all row, thirth column

array([ 4,  9, 14, 19])

In [52]:
a[::2,4]

array([ 5, 15])

### Fancy Index

In [55]:
x = np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
idxs = [2,11,5,13] #the indexes i want

In [57]:
x[idxs]

array([ 3, 12,  6, 14])

In [65]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [72]:
idxs1 = [0,1,2]

In [73]:
idxs2 = [1,3,2]

In [74]:
a[idxs1,idxs2]

array([ 2,  9, 13])

### Conditional Indexing 

In [81]:
a = np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
a < 5

array([ True,  True,  True,  True, False, False, False, False])

In [83]:
a[a<5]

array([1, 2, 3, 4])

In [11]:
x = np.array([1,2,3,4,5])

In [22]:
y = np.array([1,9,3,8,5])

In [23]:
x[x==y]

array([1, 3, 5])

In [24]:
y[x==y]

array([1, 3, 5])

***or = |***

***and = &***

In [26]:
a = np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True])

In [30]:
(a < 5) & (a > 2)

array([False, False,  True,  True, False, False, False, False])

***not = ~***

In [31]:
filt = ~((a < 3) | (a > 5))

In [32]:
filt

array([False, False,  True,  True,  True, False, False, False])

## SUM

In [7]:
a = np.arange(1,11).reshape(2,5)

In [8]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
np.sum(a)

55

In [14]:
filt = a > 5

In [15]:
filt

[array([[False, False, False, False, False],
        [ True,  True,  True,  True,  True]])]

In [17]:
np.sum(filt)

5

In [22]:
a[tuple(filt)] # a[tuple(filt)] = a[filt]

array([ 6,  7,  8,  9, 10])

In [24]:
np.sum(a[tuple(filt)]) #np.sum(a[tuple(filt)]) = np.sum(a[filt])

40

In [25]:
np.sum(a, axis = 0)

array([ 7,  9, 11, 13, 15])

In [26]:
np.sum(a, axis = 1)

array([15, 40])

In [30]:
a=np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
np.sum(a,axis=0)

array([34, 38, 42, 46, 50])

In [32]:
np.sum(a,axis=0).shape 

(5,)

## ALL

In [33]:
x = np.arange(1,21).reshape(4,5)

In [34]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
filt = x > -1
filt

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [41]:
np.all(filt)

True

In [49]:
np.all(filt , axis = 1)

array([ True,  True,  True,  True])

In [51]:
filt2 = x > 6
filt2

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [52]:
np.all(filt2)

False

In [53]:
np.all(filt2 , axis = 1)

array([False, False,  True,  True])

## ANY

In [57]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [59]:
a > 9

array([[False, False, False, False, False],
       [False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [58]:
np.any(a > 9 , axis = 1)

array([False,  True,  True])

# Equation with Two Unknowns with Numpy

5x0 + x1 = 12

x0 + 3x1 = 10

In [60]:
a = np.array([[5,1],[1,3]])
a

array([[5, 1],
       [1, 3]])

In [62]:
b = np.array([12,10])
b

array([12, 10])

In [64]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])