## ARRAY OPERATIONS

In [2]:
import numpy as np

In [11]:
x = np.array([2,3,4])
y = np.array([5,4,1])

x*y

array([10, 12,  4])

In [12]:
x+y

array([7, 7, 5])

In [13]:
2 * x

array([4, 6, 8])

In [14]:
x = 3 * x  #update value
x

array([ 6,  9, 12])

## UFUNC 

**SUBTRACT**

In [19]:
a = np.array([5,10,15,20])
a

array([ 5, 10, 15, 20])

In [20]:
np.subtract(a,1) 

array([ 4,  9, 14, 19])

**ADD**

In [21]:
np.add(a,1) 

array([ 6, 11, 16, 21])

**MULTIPLY**

In [22]:
np.multiply(a,3) 

array([15, 30, 45, 60])

**DIVIDE**

In [24]:
np.divide(a,3) 

array([1.66666667, 3.33333333, 5.        , 6.66666667])

**POWER**

In [25]:
np.power(a,3) 

array([ 125, 1000, 3375, 8000])

**MOD**

In [26]:
np.mod(a,3) 

array([2, 1, 0, 2])

**ABSOLUTE** (mutlak değer)

In [27]:
np.absolute(np.array([-1]))

array([1])

**SIN & COS**

In [28]:
np.sin(360)

0.9589157234143065

In [31]:
np.cos(90)

-0.4480736161291701

**LOG**

In [32]:
v = np.array([1,2,3])
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [33]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [34]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [3]:
?np

## ARRAY ATTRIBUTE

### SHAPE 

dimension info

In [24]:
x = np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
x.shape

(2, 3)

In [26]:
y = np.ones((3,4,2))
y

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [27]:
y.shape

(3, 4, 2)

### NDIM

dimension number

In [28]:
x = np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
x.ndim

2

In [30]:
y = np.ones((3,4,2))
y

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [31]:
y.ndim

3

### SIZE 

total number of elements

In [32]:
y = np.ones((2,4,5))
y

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [33]:
y.size

40

### DTYPE 

array data type

In [34]:
x = np.zeros((2,3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
x.dtype

dtype('float64')

## RESHAPE 

the dimensions must be the same

In [37]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
a.shape

(10,)

In [38]:
a.ndim

1

In [39]:
a.size

10

In [43]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [44]:
a.reshape(5,2).ndim

2

In [45]:
a.reshape(5,2).size

10

### Dimension with -1 

In [50]:
a.reshape(-1,2) #it finds that 5

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Add New Dimension 

In [51]:
a[np.newaxis , :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [55]:
a.shape

(10,)

In [52]:
a[np.newaxis , :].shape

(1, 10)

In [58]:
a[:, np.newaxis] #column vector

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [57]:
a[:, np.newaxis].shape

(10, 1)

or None

In [59]:
a[None,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [60]:
a[:,None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

## CONCATENATION 

In [63]:
a = np.arange(4,8)
a

array([4, 5, 6, 7])

In [65]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [68]:
np.concatenate([a,b])

array([4, 5, 6, 7, 1, 2, 3, 4])

In [73]:
list = [9,8,"c"]

In [74]:
np.concatenate([a,b,list])

array(['4', '5', '6', '7', '1', '2', '3', '4', '9', '8', 'c'],
      dtype='<U21')

In [71]:
tuple = (11,12)

In [75]:
np.concatenate([a,b,tuple])

array([ 4,  5,  6,  7,  1,  2,  3,  4, 11, 12])

### Size Mismatch

In [77]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [80]:
x = np.array([[1,2,3],
             [4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
a.shape

(4,)

In [83]:
x.shape

(2, 3)

In [84]:
np.concatenate([a,x]) #error

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [85]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.concatenate([x,x]) #axis=0 add to row

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

default --> row axis = 0
            column axis = 1

In [89]:
np.concatenate([x,x], axis =1) #axis=1 add to column

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## [HACKERRANK EXAMPLE](https://www.hackerrank.com/challenges/np-concatenate/problem)

You are given two integer arrays of size N X P and M X P ( N & M are rows, and P is the column). Your task is to concatenate the arrays along axis .

Input Format
The first line contains space separated integers N , M and P. 

The next N lines contains the space separated elements of the P columns. 

After that, the next M lines contains the space separated elements of the P columns.

SAMPLE INPUT

```
4 3 2

1 2
1 2
1 2
1 2
3 4
3 4
3 4
```



SAMPLE OUTPUT

` ` `
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]
 ` ` `


## SOLUTION

In [7]:
import numpy as np

a, b, c = map(int,input().split())
arrA = np.array([input().split() for _ in range(a)],int)
arrB = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arrA, arrB), axis = 0))

1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## STACK

In [9]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [10]:
b = np.array([3,4,5,6])
b

array([3, 4, 5, 6])

In [11]:
np.stack([a,b]) #axis=0 add to row

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [23]:
np.stack([a,b], axis=1) #axis=1 add to column

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])