# NUMPY

In [3]:
import numpy as np

In [4]:
a = np.array([2,4,6,8])
b = np.array([1,2,3,4])

In [5]:
a*b

array([ 2,  8, 18, 32])

In [6]:
type(a)

numpy.ndarray

## CREATING AN ARRAY

In [4]:
np.array([4.3,6,9,2], dtype = float)

array([4.3, 6. , 9. , 2. ])

We could have written "int" instead of "float".

 ### ZEROS

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.zeros(10, dtype = int) #just 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.zeros([3,8,8]) #multidimensional

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0

In [8]:
np.zeros((3,2), dtype = bool) #zero=False in bool

array([[False, False],
       [False, False],
       [False, False]])

### ONES

In [21]:
np.ones((2,5), dtype = int) #just 1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### FULL

In [26]:
np.full((2,6),3) #just the number i want

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [4]:
np.full(5,3)

array([3, 3, 3, 3, 3])

### CONSEQUTİVE NUMBERS ARRAY


In [5]:
#[x,y)
np.arange(3,28,4) 

array([ 3,  7, 11, 15, 19, 23, 27])

### DIVIDING INTERVAL

In [6]:
#[x,y]
np.linspace(0,1) #default=50

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [26]:
np.linspace(2,4,6)

array([2. , 2.4, 2.8, 3.2, 3.6, 4. ])

## NORMAL DISTRIBUTION ARRAY

In [27]:
np.random.normal()

-0.27236808686056363

- (mean, std, array size)

In [28]:
np.random.normal(0,3,(4,5))

array([[ 1.11406662,  0.34784251,  3.8142287 ,  4.89966567, -1.14818829],
       [ 6.27089436,  1.79914701, -0.60556123,  1.02994124, -3.30224184],
       [ 1.56340918, -2.85776465,  4.93237383, -2.14541002, -1.17389075],
       [ 3.92087909,  0.41087614, -1.66561509,  1.62424442, -0.96491895]])

## RANDOM INTEGER ARRAY

- [low,high)

In [31]:
np.random.randint(1,10,(3,4))

array([[1, 8, 5, 8],
       [4, 1, 7, 4],
       [6, 2, 7, 9]])

In [34]:
np.random.randint(1,50,(2,3,4))

array([[[40, 17, 48, 46],
        [ 7, 35, 17, 16],
        [ 5, 35, 30, 49]],

       [[22, 11, 49,  4],
        [ 7, 41, 19, 21],
        [18, 48, 17, 45]]])

In [45]:
d = {}
for _ in range(15000):
   val =  np.random.randint(1,11)
    
   if val not in d:
    d[val] = 1
   else:
    d[val] += 1

In [46]:
d

{3: 1573,
 9: 1477,
 7: 1541,
 5: 1418,
 4: 1547,
 6: 1473,
 1: 1455,
 10: 1490,
 2: 1444,
 8: 1582}

## IDENTITY MATRIX

- [low,high)

In [3]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
np.eye(3,4) #incomplete

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])